# Generated by Django 5.0.6 on 2024-07-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rag', '0002_page_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.CreateModel(
            name='Question_and_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Rag.page')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
